# Generated by Django 6.0.3 on 2026-04-07 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('medical', 'Medical'), ('legal', 'Legal'), ('counseling', 'Counseling'), ('shelter', 'Shelter'), ('hotline', 'Hotline'), ('ngo', 'NGO'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('incident_type', models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('psychological', 'Psychological / Emotional Abuse'), ('economic', 'Economic Abuse'), ('harmful_practice', 'Harmful Traditional Practice'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_to_followup', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
