# Generated by Django 6.0.3 on 2026-04-01 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Resource Name')),
                ('type', models.CharField(choices=[('medical', 'Medical / Health Services'), ('legal', 'Legal Aid'), ('counseling', 'Psychological Counseling'), ('shelter', 'Safe Shelter'), ('hotline', 'Emergency Hotline'), ('ngo', 'NGO / Support Organization'), ('other', 'Other')], max_length=50, verbose_name='Service Type')),
                ('description', models.TextField(blank=True, verbose_name='Brief Description')),
                ('location', models.CharField(max_length=200, verbose_name='Location (Tigray Region)')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('incident_type', models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('psychological', 'Psychological/Emotional Abuse'), ('economic', 'Economic Abuse'), ('harmful_practice', 'Harmful Traditional Practice'), ('other', 'Other')], max_length=50, verbose_name='Type of Violence')),
                ('description', models.TextField(verbose_name='Description of the Incident')),
                ('location', models.CharField(max_length=255, verbose_name='Location (Zone/Woreda in Tigray)')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='Date of Incident')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Report Anonymously')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name (optional)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number (optional)')),
                ('consent_to_followup', models.BooleanField(default=False, verbose_name='I consent to follow-up contact')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GBV Report',
                'verbose_name_plural': 'GBV Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
