# Generated by Django 6.0.3 on 2026-03-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='report',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
